### ISSUE TITLE
After updating to version 2.1, confirmation beep no longer plays.

### ISSUE THREAD

**Issue by blindninja97** [NVDARemote/NVDARemote#167]
After updating to version 2.1, the double beep that tells you you yourself have connected to the host plays correctly, however the old confirmation beep that used to play when the other computer connected with the same key and your connection was actually established seems to be broken, and I wasn't aware that the connection had actually succeeded until I attempted doing something. However I have only just now updated and had the opportunity to test once, so this may have just been a one-time issue.

**Comment by tech10** [comment]
The beep is still there, but it's difficult to notice if you're not really paying attention to it. Since the beeps no longer block, they won't sound in sequence with each other, and you can't play more than one at a time.

So, on mine, for example, you have the two beeps that play in assending sequence when you connect successfully to a server, then you have the higher, longer beep that confirms a client connected. However, my beeps will play like this. First tone of a successful connection begins, interrupted by the long successful beep of a client connection, then interrupted by the second tone of a successful connection. It's strange, but that's how it works currently. Better that and perhaps removing some of the beeps, or finding another way to play them such as a sound file perhaps, than blocking NVDA with the beeps, in my opinion. I always thought it would be useful to have an option for speech to tell you all events rather than beeps, myself, just in case someone didn't want or like the beeps.

**Comment by alekssamos** [comment]
> However, my beeps will play like this. First tone of a successful connection begins, interrupted by the long successful beep of a client connection, then interrupted by the second tone of a successful connection.

I noticed that, too.
Still relevant.

**Comment by ctoth** [comment]
This has been resolved with the introduction of true earcon audio cues.
