### ISSUE TITLE
NVDA 2019.3 support or more later

### ISSUE THREAD

**Issue by Nikita34196** [NVDARemote/NVDARemote#207]
Hello. NVDA 2019.3 will be on python3. When are you planning to update the add-on to support this version?

**Comment by tyrylu** [comment]
Would really be helpful. Or, would you accept a PR?

**Comment by destroyersboy** [comment]
I haven't had much opportunity to review, but there are branches in this repo about python3.

You should try them?

I've seen it in NVDA's Issue, they were talking to add-on manufacturers about it. The remote must be among them.

This is a great project.

**Comment by leonardder** [comment]
I investigated the impact of speech refactor. The Python 3 update itself isn't that challenging, running the code through 2to3 or python-modernize should already do most of the work. I'm afraid https://github.com/NVDARemote/NVDARemote/pull/183 won't be of any help here.

Re speech refactor, we now have a nice speech manager that is very capable of adding indexes to speech sequences. Therefore, I propose the following

* Remove all code that deals wit indexes. That code was buggy anyway, i.e. it causes stuff to fail when the master system has the synth turned off.
* Instead of patching the synth, patch speech._manager.speak and speech._manager.cancel

**Comment by gdata1** [comment]
I hope by the release of nvda 2019.3 the supplement will be available. I'm already forced not to use alfa versions because I often use nvda remote.
